name: Publish

on:
  release:
    types: [prereleased, released]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ github.event.release.tag_name }}

  upload-release-artifacts:
    name: Add artifacts to Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Upload artifacts to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
        run: gh release upload ${{ github.event.release.tag_name }} thunderstore-build/*/dist/*.zip nupkg-build/*/bin/Release/*.nupkg

  release-curseforge:
    needs: build
    uses: ./.github/workflows/release-curseforge.yml
    secrets:
      curseforge-token: ${{ secrets.CURSEFORGE_API_KEY }}
      project-id: ${{ secrets.CURSEFORGE_PROJECTID }}

  release-thunderstore:
    needs: build
    uses: ./.github/workflows/release-thunderstore.yml
    secrets:
      thunderstore-token: ${{ secrets.THUNDERSTORE_API_KEY }}

  release-nuget:
    needs: build
    uses: ./.github/workflows/release-nuget.yml
    secrets:
      nuget-token: ${{ secrets.NUGET_API_KEY }}