name: Release on Curseforge

on:
  workflow_call:
    secrets:
      curseforge-token:
        required: true
      project-id:
        required: true

jobs:
  curseforge:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Download Curseforge artifact
        uses: actions/download-artifact@v4
        with:
          name: curseforge-build

      - name: Download Versions artifact
        uses: actions/download-artifact@v4
        with:
          name: versions

      - name: Set MOD_NAME environment variable
        run: echo "MOD_NAME=$(cat ./*/dist/name.txt )" >> $GITHUB_ENV

      - name: Set MOD_VERSION environment variable
        run: echo "MOD_VERSION=$(cat ./*/dist/version.txt )" >> $GITHUB_ENV

      - name: Set ZIP_PATH environment variable
        run: echo "ZIP_PATH=./${{ env.MOD_NAME }}/dist/curseforge.zip" >> $GITHUB_ENV

      - name: "Upload to CurseForge"
        uses: itsmeow/curseforge-upload@v3
        with:
          token: ${{ secrets.curseforge-token }}
          project_id: ${{ secrets.project-id }}
          game_endpoint: "lethal-company"
          game_versions: "0.50.0"
          file_path: ${{ env.ZIP_PATH }}
          display_name: ${{ env.MOD_NAME }} v${{ env.MOD_VERSION }}